// ═════════════════════════════════════════════════════════════════════════
// 《2026–2027 猶太讀經循環：年度通讀手冊與伴讀工具包》靜態資料核心
// 品牌：釐經伴道 @shmuel310 (基督信仰 · 聖經詮釋 · AI應用)
// ═════════════════════════════════════════════════════════════════════════

const COMPANION_DATA = {
  brand: {
  "name": "釐經伴道",
  "handle": "@shmuel310",
  "pillars": "基督信仰 · 聖經詮釋 · AI應用",
  "slogan": "以文字梳理聖言，以工具釐清脈絡",
  "instagram": "https://www.instagram.com/shmuel310",
  "qr_instagram": "companion_assets/qr_instagram.svg",
  "year_gregorian": "2026–2027",
  "year_hebrew": "5787",
  "title": "2026–2027 猶太讀經循環：年度通讀手冊與伴讀工具包",
  "subtitle": "信徒未來一年每週必備的導航儀 · 猶太曆 5787"
},
  parashot: [
  {
    "id": 1,
    "name": "Bereshit",
    "name_he": "בְּרֵאשִׁית",
    "name_zh": "起初篇",
    "book": "Gen",
    "book_zh": "創世記",
    "range": "1:1-6:8",
    "range_zh": "創世記 1:1-6:8",
    "gdate": "2026-10-10",
    "hdate": "29 Tishrei",
    "tool": "lifespan",
    "tool_name": "先祖壽命圖",
    "count": 1,
    "note": "循環啟程 · 創造天地與墮落"
  },
  {
    "id": 2,
    "name": "Noach",
    "name_he": "נֹחַ",
    "name_zh": "挪亞篇",
    "book": "Gen",
    "book_zh": "創世記",
    "range": "6:9-11:32",
    "range_zh": "創世記 6:9-11:32",
    "gdate": "2026-10-17",
    "hdate": "6 Cheshvan",
    "tool": "lifespan",
    "tool_name": "先祖壽命圖",
    "count": 0,
    "note": "大洪水 · 挪亞之約 · 巴別塔"
  },
  {
    "id": 3,
    "name": "Lech-Lecha",
    "name_he": "לֶךְ־לְךָ",
    "name_zh": "你要離開篇",
    "book": "Gen",
    "book_zh": "創世記",
    "range": "12:1-17:27",
    "range_zh": "創世記 12:1-17:27",
    "gdate": "2026-10-24",
    "hdate": "13 Cheshvan",
    "tool": "genfam",
    "tool_name": "家族譜系圖",
    "count": 0,
    "note": "亞伯蘭受召 · 應許之約 · 割禮"
  },
  {
    "id": 4,
    "name": "Vayera",
    "name_he": "וַיֵּרָא",
    "name_zh": "顯現篇",
    "book": "Gen",
    "book_zh": "創世記",
    "range": "18:1-22:24",
    "range_zh": "創世記 18:1-22:24",
    "gdate": "2026-10-31",
    "hdate": "20 Cheshvan",
    "tool": "genfam",
    "tool_name": "家族譜系圖",
    "count": 0,
    "note": "接待天使 · 所多瑪毀滅 · 獻以撒"
  },
  {
    "id": 5,
    "name": "Chayei Sara",
    "name_he": "חַיֵּי שָׂרָה",
    "name_zh": "撒拉的壽數篇",
    "book": "Gen",
    "book_zh": "創世記",
    "range": "23:1-25:18",
    "range_zh": "創世記 23:1-25:18",
    "gdate": "2026-11-07",
    "hdate": "27 Cheshvan",
    "tool": "genfam",
    "tool_name": "家族譜系圖",
    "count": 0,
    "note": "麥比拉洞葬撒拉 · 以撒娶利百加"
  },
  {
    "id": 6,
    "name": "Toldot",
    "name_he": "תּוֹלְדֹת",
    "name_zh": "後代篇",
    "book": "Gen",
    "book_zh": "創世記",
    "range": "25:19-28:9",
    "range_zh": "創世記 25:19-28:9",
    "gdate": "2026-11-14",
    "hdate": "4 Kislev",
    "tool": "genfam",
    "tool_name": "家族譜系圖",
    "count": 0,
    "note": "以掃與雅各 · 長子名份 · 井之爭"
  },
  {
    "id": 7,
    "name": "Vayetzei",
    "name_he": "וַיֵּצֵא",
    "name_zh": "出來篇",
    "book": "Gen",
    "book_zh": "創世記",
    "range": "28:10-32:3",
    "range_zh": "創世記 28:10-32:3",
    "gdate": "2026-11-21",
    "hdate": "11 Kislev",
    "tool": "genfam",
    "tool_name": "家族譜系圖",
    "count": 0,
    "note": "伯特利天梯 · 拉班家二十年 · 十二子出世"
  },
  {
    "id": 8,
    "name": "Vayishlach",
    "name_he": "וַיִּשְׁלַח",
    "name_zh": "打發篇",
    "book": "Gen",
    "book_zh": "創世記",
    "range": "32:4-36:43",
    "range_zh": "創世記 32:4-36:43",
    "gdate": "2026-11-28",
    "hdate": "18 Kislev",
    "tool": "genfam",
    "tool_name": "家族譜系圖",
    "count": 0,
    "note": "雅博渡口摔跤 · 改名以色列 · 與以掃和解"
  },
  {
    "id": 9,
    "name": "Vayeshev",
    "name_he": "וַיֵּשֶׁב",
    "name_zh": "住下篇",
    "book": "Gen",
    "book_zh": "創世記",
    "range": "37:1-40:23",
    "range_zh": "創世記 37:1-40:23",
    "gdate": "2026-12-05",
    "hdate": "25 Kislev",
    "tool": "genfam",
    "tool_name": "家族譜系圖",
    "count": 0,
    "note": "光明節第1日 · 約瑟被賣 · 他瑪與猶大"
  },
  {
    "id": 10,
    "name": "Miketz",
    "name_he": "מִקֵּץ",
    "name_zh": "過了篇",
    "book": "Gen",
    "book_zh": "創世記",
    "range": "41:1-44:17",
    "range_zh": "創世記 41:1-44:17",
    "gdate": "2026-12-12",
    "hdate": "2 Tevet",
    "tool": "genfam",
    "tool_name": "家族譜系圖",
    "count": 0,
    "note": "光明節第8日 · 法老解夢 · 約瑟為埃及宰相"
  },
  {
    "id": 11,
    "name": "Vayigash",
    "name_he": "וַיִּגַּשׁ",
    "name_zh": "挨近篇",
    "book": "Gen",
    "book_zh": "創世記",
    "range": "44:18-47:27",
    "range_zh": "創世記 44:18-47:27",
    "gdate": "2026-12-19",
    "hdate": "9 Tevet",
    "tool": "genfam",
    "tool_name": "家族譜系圖",
    "count": 0,
    "note": "約瑟與弟兄相認 · 雅各全家下埃及"
  },
  {
    "id": 12,
    "name": "Vayechi",
    "name_he": "וַיְחִי",
    "name_zh": "活著篇",
    "book": "Gen",
    "book_zh": "創世記",
    "range": "47:28-50:26",
    "range_zh": "創世記 47:28-50:26",
    "gdate": "2026-12-26",
    "hdate": "16 Tevet",
    "tool": "genfam",
    "tool_name": "家族譜系圖",
    "count": 0,
    "note": "創世記圓滿 · 雅各祝福十二支派 · 臨終遺命"
  },
  {
    "id": 13,
    "name": "Shemot",
    "name_he": "שְׁמוֹת",
    "name_zh": "名字篇",
    "book": "Exo",
    "book_zh": "出埃及記",
    "range": "1:1-6:1",
    "range_zh": "出埃及記 1:1-6:1",
    "gdate": "2027-01-02",
    "hdate": "23 Tevet",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 0,
    "note": "以色列人為奴 · 摩西出世 · 燃燒荊棘受差"
  },
  {
    "id": 14,
    "name": "Vaera",
    "name_he": "וָאֵרָא",
    "name_zh": "顯現篇",
    "book": "Exo",
    "book_zh": "出埃及記",
    "range": "6:2-9:35",
    "range_zh": "出埃及記 6:2-9:35",
    "gdate": "2027-01-09",
    "hdate": "1 Sh'vat",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 0,
    "note": "立約神聖之名 · 前七大災難降臨埃及"
  },
  {
    "id": 15,
    "name": "Bo",
    "name_he": "בֹּא",
    "name_zh": "進去篇",
    "book": "Exo",
    "book_zh": "出埃及記",
    "range": "10:1-13:16",
    "range_zh": "出埃及記 10:1-13:16",
    "gdate": "2027-01-16",
    "hdate": "8 Sh'vat",
    "tool": "calendar",
    "tool_name": "猶太曆法",
    "count": 20,
    "note": "最後三災 · 逾越節羔羊 · 擊殺長子 · 正月之首"
  },
  {
    "id": 16,
    "name": "Beshalach",
    "name_he": "בְּשַׁלַּח",
    "name_zh": "放去篇",
    "book": "Exo",
    "book_zh": "出埃及記",
    "range": "13:17-17:16",
    "range_zh": "出埃及記 13:17-17:16",
    "gdate": "2027-01-23",
    "hdate": "15 Sh'vat",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 1,
    "note": "詩歌安息日 · 過紅海 · 雲柱火柱 · 降嗎哪"
  },
  {
    "id": 17,
    "name": "Yitro",
    "name_he": "יִתְרוֹ",
    "name_zh": "葉忒羅篇",
    "book": "Exo",
    "book_zh": "出埃及記",
    "range": "18:1-20:23",
    "range_zh": "出埃及記 18:1-20:23",
    "gdate": "2027-01-30",
    "hdate": "22 Sh'vat",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 17,
    "note": "西奈山立約 · 神親口頒佈十誡 (Aseret HaDibrot)"
  },
  {
    "id": 18,
    "name": "Mishpatim",
    "name_he": "מִשְׁפָּטִים",
    "name_zh": "典章篇",
    "book": "Exo",
    "book_zh": "出埃及記",
    "range": "21:1-24:18",
    "range_zh": "出埃及記 21:1-24:18",
    "gdate": "2027-02-06",
    "hdate": "29 Sh'vat",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 53,
    "note": "公民民法 · 奴僕賠償 · 約書血祭確認"
  },
  {
    "id": 19,
    "name": "Terumah",
    "name_he": "תְּרוּמָה",
    "name_zh": "禮物篇",
    "book": "Exo",
    "book_zh": "出埃及記",
    "range": "25:1-27:19",
    "range_zh": "出埃及記 25:1-27:19",
    "gdate": "2027-02-13",
    "hdate": "6 Adar I",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 3,
    "note": "造會幕藍圖 · 約櫃 · 金燈臺 · 陳設餅桌"
  },
  {
    "id": 20,
    "name": "Tetzaveh",
    "name_he": "תְּצַוֶּה",
    "name_zh": "吩咐篇",
    "book": "Exo",
    "book_zh": "出埃及記",
    "range": "27:20-30:10",
    "range_zh": "出埃及記 27:20-30:10",
    "gdate": "2027-02-20",
    "hdate": "13 Adar I",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 7,
    "note": "聖膏油與祭司聖服 · 以弗得胸牌 · 金香壇"
  },
  {
    "id": 21,
    "name": "Ki Tisa",
    "name_he": "כִּי תִשָּׂא",
    "name_zh": "數點篇",
    "book": "Exo",
    "book_zh": "出埃及記",
    "range": "30:11-34:35",
    "range_zh": "出埃及記 30:11-34:35",
    "gdate": "2027-02-27",
    "hdate": "20 Adar I",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 9,
    "note": "金牛犢背約 · 摔碎石版 · 摩西代求 · 重頒十誡"
  },
  {
    "id": 22,
    "name": "Vayakhel",
    "name_he": "וַיַּקְהֵל",
    "name_zh": "招聚篇",
    "book": "Exo",
    "book_zh": "出埃及記",
    "range": "35:1-38:20",
    "range_zh": "出埃及記 35:1-38:20",
    "gdate": "2027-03-06",
    "hdate": "27 Adar I",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 1,
    "note": "甘心樂意奉獻 · 聖靈充滿比撒列建造會幕"
  },
  {
    "id": 23,
    "name": "Pekudei",
    "name_he": "פְקוּדֵי",
    "name_zh": "數點篇",
    "book": "Exo",
    "book_zh": "出埃及記",
    "range": "38:21-40:38",
    "range_zh": "出埃及記 38:21-40:38",
    "gdate": "2027-03-13",
    "hdate": "4 Adar II",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 0,
    "note": "出埃及記圓滿 · 會幕立起 · 耶和華榮光充滿"
  },
  {
    "id": 24,
    "name": "Vayikra",
    "name_he": "וַיִּקְרָא",
    "name_zh": "呼叫篇",
    "book": "Lev",
    "book_zh": "利未記",
    "range": "1:1-5:26",
    "range_zh": "利未記 1:1-5:26",
    "gdate": "2027-03-20",
    "hdate": "11 Adar II",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 16,
    "note": "五大祭禮：燔祭、素祭、平安祭、贖罪祭、贖愆祭"
  },
  {
    "id": 25,
    "name": "Tzav",
    "name_he": "צַו",
    "name_zh": "命令篇",
    "book": "Lev",
    "book_zh": "利未記",
    "range": "6:1-8:36",
    "range_zh": "利未記 6:1-8:36",
    "gdate": "2027-03-27",
    "hdate": "18 Adar II",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 18,
    "note": "壇上之火不可熄滅 · 亞倫與其子受膏承接聖職"
  },
  {
    "id": 26,
    "name": "Shmini",
    "name_he": "שְׁמִינִי",
    "name_zh": "第八篇",
    "book": "Lev",
    "book_zh": "利未記",
    "range": "9:1-11:47",
    "range_zh": "利未記 9:1-11:47",
    "gdate": "2027-04-03",
    "hdate": "25 Adar II",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 17,
    "note": "拿答亞比戶獻凡火 · 潔淨飲食規矩 (Kosher)"
  },
  {
    "id": 27,
    "name": "Tazria",
    "name_he": "תַּזְרִיעַ",
    "name_zh": "懷孕篇",
    "book": "Lev",
    "book_zh": "利未記",
    "range": "12:1-13:59",
    "range_zh": "利未記 12:1-13:59",
    "gdate": "2027-04-10",
    "hdate": "3 Nisan",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 5,
    "note": "產婦產後潔淨 · 大痲瘋皮膚病之診斷與隔離"
  },
  {
    "id": 28,
    "name": "Metzora",
    "name_he": "מְּצֹרָע",
    "name_zh": "長大痲瘋篇",
    "book": "Lev",
    "book_zh": "利未記",
    "range": "14:1-15:33",
    "range_zh": "利未記 14:1-15:33",
    "gdate": "2027-04-17",
    "hdate": "10 Nisan",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 11,
    "note": "大安息日 Shab. HaGadol · 痲瘋潔淨之禮 · 活鳥血洗"
  },
  {
    "id": 29,
    "name": "Achrei Mot",
    "name_he": "אַחֲרֵי מוֹת",
    "name_zh": "死後篇",
    "book": "Lev",
    "book_zh": "利未記",
    "range": "16:1-18:30",
    "range_zh": "利未記 16:1-18:30",
    "gdate": "2027-05-01",
    "hdate": "24 Nisan",
    "tool": "calendar",
    "tool_name": "猶太曆法",
    "count": 28,
    "note": "五經樞紐：贖罪日大祭禮 · 代罪羔羊阿撒瀉勒 · 聖潔生活"
  },
  {
    "id": 30,
    "name": "Kedoshim",
    "name_he": "קְדֹשִׁים",
    "name_zh": "聖潔篇",
    "book": "Lev",
    "book_zh": "利未記",
    "range": "19:1-20:27",
    "range_zh": "利未記 19:1-20:27",
    "gdate": "2027-05-08",
    "hdate": "1 Iyyar",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 51,
    "note": "你們要聖潔因為我是聖潔的 · 愛人如己 (Lev 19:18)"
  },
  {
    "id": 31,
    "name": "Emor",
    "name_he": "אֱמֹר",
    "name_zh": "你說篇",
    "book": "Lev",
    "book_zh": "利未記",
    "range": "21:1-24:23",
    "range_zh": "利未記 21:1-24:23",
    "gdate": "2027-05-15",
    "hdate": "8 Iyyar",
    "tool": "calendar",
    "tool_name": "猶太曆法",
    "count": 63,
    "note": "祭司聖潔規矩 · 耶和華七大節期總覽 (安息/春節/秋節)"
  },
  {
    "id": 32,
    "name": "Behar",
    "name_he": "בְּהַר",
    "name_zh": "在山上篇",
    "book": "Lev",
    "book_zh": "利未記",
    "range": "25:1-26:2",
    "range_zh": "利未記 25:1-26:2",
    "gdate": "2027-05-22",
    "hdate": "15 Iyyar",
    "tool": "calendar",
    "tool_name": "猶太曆法",
    "count": 24,
    "note": "第七年安息年 · 第五十年禧年宣告 · 土地與奴僕贖回"
  },
  {
    "id": 33,
    "name": "Bechukotai",
    "name_he": "בְּחֻקֹּתַי",
    "name_zh": "我的律例篇",
    "book": "Lev",
    "book_zh": "利未記",
    "range": "26:3-27:34",
    "range_zh": "利未記 26:3-27:34",
    "gdate": "2027-05-29",
    "hdate": "22 Iyyar",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 12,
    "note": "利未記圓滿 · 順服與悖逆之福禍 · 許願與十分之一"
  },
  {
    "id": 34,
    "name": "Bamidbar",
    "name_he": "בְּמִדְבַּר",
    "name_zh": "在曠野篇",
    "book": "Num",
    "book_zh": "民數記",
    "range": "1:1-4:20",
    "range_zh": "民數記 1:1-4:20",
    "gdate": "2027-06-05",
    "hdate": "29 Iyyar",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 0,
    "note": "第一次人口普查 · 十二支派安營紮寨與會幕守護"
  },
  {
    "id": 35,
    "name": "Nasso",
    "name_he": "נָשֹׂא",
    "name_zh": "數點篇",
    "book": "Num",
    "book_zh": "民數記",
    "range": "4:21-7:89",
    "range_zh": "民數記 4:21-7:89",
    "gdate": "2027-06-19",
    "hdate": "14 Sivan",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 18,
    "note": "拿細耳人願 · 亞倫大祭司祝福 (願耶和華賜福保護你)"
  },
  {
    "id": 36,
    "name": "Beha'alotcha",
    "name_he": "בְּהַעֲלֹתְךָ",
    "name_zh": "點燈篇",
    "book": "Num",
    "book_zh": "民數記",
    "range": "8:1-12:16",
    "range_zh": "民數記 8:1-12:16",
    "gdate": "2027-06-26",
    "hdate": "21 Sivan",
    "tool": "calendar",
    "tool_name": "猶太曆法",
    "count": 5,
    "note": "點亮金燈臺 · 銀號角 · 第二逾越節 · 百姓發怨言"
  },
  {
    "id": 37,
    "name": "Sh'lach",
    "name_he": "שְׁלַח־לְךָ",
    "name_zh": "差遣篇",
    "book": "Num",
    "book_zh": "民數記",
    "range": "13:1-15:41",
    "range_zh": "民數記 13:1-15:41",
    "gdate": "2027-07-03",
    "hdate": "28 Sivan",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 3,
    "note": "十二探子窺迦南 · 不信與四十天換四十年 · 繸子律法"
  },
  {
    "id": 38,
    "name": "Korach",
    "name_he": "קֹרַח",
    "name_zh": "可拉篇",
    "book": "Num",
    "book_zh": "民數記",
    "range": "16:1-18:32",
    "range_zh": "民數記 16:1-18:32",
    "gdate": "2027-07-10",
    "hdate": "5 Tamuz",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 9,
    "note": "可拉叛亂地裂吞滅 · 亞倫發芽開花之杖確認祭司職分"
  },
  {
    "id": 39,
    "name": "Chukat",
    "name_he": "חֻקַּת",
    "name_zh": "律例篇",
    "book": "Num",
    "book_zh": "民數記",
    "range": "19:1-22:1",
    "range_zh": "民數記 19:1-22:1",
    "gdate": "2027-07-17",
    "hdate": "12 Tamuz",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 3,
    "note": "雙篇同讀 · 紅母牛灰潔淨禮 · 擊磐出水摩西獲咎 · 銅蛇掛木架"
  },
  {
    "id": 40,
    "name": "Balak",
    "name_he": "בָּלָק",
    "name_zh": "巴勒篇",
    "book": "Num",
    "book_zh": "民數記",
    "range": "22:2-25:9",
    "range_zh": "民數記 22:2-25:9",
    "gdate": "2027-07-17",
    "hdate": "12 Tamuz",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 0,
    "note": "雙篇同讀 · 驢子開口說話 · 巴蘭咒詛變祝福 · 雅各之星"
  },
  {
    "id": 41,
    "name": "Pinchas",
    "name_he": "פִּינְחָס",
    "name_zh": "非尼哈篇",
    "book": "Num",
    "book_zh": "民數記",
    "range": "25:10-30:1",
    "range_zh": "民數記 25:10-30:1",
    "gdate": "2027-07-24",
    "hdate": "19 Tamuz",
    "tool": "calendar",
    "tool_name": "猶太曆法",
    "count": 6,
    "note": "忌邪立平安約 · 第二次普查 · 西羅非哈女兒 · 全年常獻祭"
  },
  {
    "id": 42,
    "name": "Matot",
    "name_he": "מַטּוֹת",
    "name_zh": "支派篇",
    "book": "Num",
    "book_zh": "民數記",
    "range": "30:2-32:42",
    "range_zh": "民數記 30:2-32:42",
    "gdate": "2027-07-31",
    "hdate": "26 Tamuz",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 2,
    "note": "雙篇同讀 · 許願之條例 · 報復米甸人 · 兩個半支派受河東之地"
  },
  {
    "id": 43,
    "name": "Masei",
    "name_he": "מַסְעֵי",
    "name_zh": "行程篇",
    "book": "Num",
    "book_zh": "民數記",
    "range": "33:1-36:13",
    "range_zh": "民數記 33:1-36:13",
    "gdate": "2027-07-31",
    "hdate": "26 Tamuz",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 6,
    "note": "民數記圓滿 · 曠野四十二站旅程回顧 · 劃定迦南邊界逃城"
  },
  {
    "id": 44,
    "name": "Devarim",
    "name_he": "דְּבָרִים",
    "name_zh": "話語篇",
    "book": "Deu",
    "book_zh": "申命記",
    "range": "1:1-3:22",
    "range_zh": "申命記 1:1-3:22",
    "gdate": "2027-08-07",
    "hdate": "4 Av",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 0,
    "note": "異象安息日 Shab. Chazon · 摩西在摩押平原回顧四十年曠野"
  },
  {
    "id": 45,
    "name": "Vaetchanan",
    "name_he": "וָאֶתְחַנַּן",
    "name_zh": "祈求篇",
    "book": "Deu",
    "book_zh": "申命記",
    "range": "3:23-7:11",
    "range_zh": "申命記 3:23-7:11",
    "gdate": "2027-08-14",
    "hdate": "11 Av",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 11,
    "note": "安慰安息日 · 重申十誡 · 示瑪 (Shema Yisrael: 聽啊以色列)"
  },
  {
    "id": 46,
    "name": "Eikev",
    "name_he": "עֵקֶב",
    "name_zh": "因為篇",
    "book": "Deu",
    "book_zh": "申命記",
    "range": "7:12-11:25",
    "range_zh": "申命記 7:12-11:25",
    "gdate": "2027-08-21",
    "hdate": "18 Av",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 8,
    "note": "人活著不是單靠食物乃靠神口裡的話 · 七種土產流奶與蜜"
  },
  {
    "id": 47,
    "name": "Re'eh",
    "name_he": "רְאֵה",
    "name_zh": "你看篇",
    "book": "Deu",
    "book_zh": "申命記",
    "range": "11:26-16:17",
    "range_zh": "申命記 11:26-16:17",
    "gdate": "2027-08-28",
    "hdate": "25 Av",
    "tool": "calendar",
    "tool_name": "猶太曆法",
    "count": 55,
    "note": "陳明祝福與咒詛 · 唯一敬拜中樞之所 · 豁免年與三大節期"
  },
  {
    "id": 48,
    "name": "Shoftim",
    "name_he": "שֹׁפְטִים",
    "name_zh": "審判官篇",
    "book": "Deu",
    "book_zh": "申命記",
    "range": "16:18-21:9",
    "range_zh": "申命記 16:18-21:9",
    "gdate": "2027-09-04",
    "hdate": "2 Elul",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 41,
    "note": "追求公義公平 · 立王治國之法 · 預言像摩西的先知興起"
  },
  {
    "id": 49,
    "name": "Ki Teitzei",
    "name_he": "כִּי־תֵצֵא",
    "name_zh": "出去篇",
    "book": "Deu",
    "book_zh": "申命記",
    "range": "21:10-25:19",
    "range_zh": "申命記 21:10-25:19",
    "gdate": "2027-09-11",
    "hdate": "9 Elul",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 74,
    "note": "五經中誡命最多的一週（74條）· 公民道德、家庭與憐憫"
  },
  {
    "id": 50,
    "name": "Ki Tavo",
    "name_he": "כִּי־תָבוֹא",
    "name_zh": "進去篇",
    "book": "Deu",
    "book_zh": "申命記",
    "range": "26:1-29:8",
    "range_zh": "申命記 26:1-29:8",
    "gdate": "2027-09-18",
    "hdate": "16 Elul",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 6,
    "note": "初熟之物宣告 · 基利心山祝福與以巴路山咒詛宣讀"
  },
  {
    "id": 51,
    "name": "Nitzavim",
    "name_he": "נִצָּבִים",
    "name_zh": "站立篇",
    "book": "Deu",
    "book_zh": "申命記",
    "range": "29:9-30:20",
    "range_zh": "申命記 29:9-30:20",
    "gdate": "2027-09-25",
    "hdate": "23 Elul",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 0,
    "note": "雙篇同讀 · 今日與神重新立約 · 選擇生命 · 這話離你不遠"
  },
  {
    "id": 52,
    "name": "Vayelech",
    "name_he": "וַיֵּלֶךְ",
    "name_zh": "去篇",
    "book": "Deu",
    "book_zh": "申命記",
    "range": "31:1-30",
    "range_zh": "申命記 31:1-30",
    "gdate": "2027-09-25",
    "hdate": "23 Elul",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 2,
    "note": "摩西交付統帥權與約書 · 約書亞剛強壯膽 · 妥拉誦讀規矩"
  },
  {
    "id": 53,
    "name": "Haazinu",
    "name_he": "הַאֲזִינוּ",
    "name_zh": "側耳聽篇",
    "book": "Deu",
    "book_zh": "申命記",
    "range": "32:1-52",
    "range_zh": "申命記 32:1-52",
    "gdate": "2027-10-09",
    "hdate": "8 Tishrei 5788",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 0,
    "note": "回轉安息日 Shab. Shuva · 摩西偉大詩歌 · 磐石信實完全"
  },
  {
    "id": 54,
    "name": "VZot HaBerachah",
    "name_he": "וְזֹאת הַבְּרָכָה",
    "name_zh": "這是祝福篇",
    "book": "Deu",
    "book_zh": "申命記",
    "range": "33:1-34:12",
    "range_zh": "申命記 33:1-34:12",
    "gdate": "2027-10-24",
    "hdate": "23 Tishrei 5788",
    "tool": "explorer",
    "tool_name": "五經全覽",
    "count": 0,
    "note": "妥拉節 Simchat Torah 圓滿收卷 · 摩西祝福十二支派 · 尼波山長眠"
  }
],
  tools: [
  {
    "id": "lifespan",
    "name": "創世記先祖壽命圖譜",
    "subtitle": "Genesis Patriarchs Lifespan Timeline",
    "url": "https://shmuel310.github.io/genesis_patriarchs_lifespan/",
    "qr": "companion_assets/qr_lifespan.svg",
    "weeks": "第 1–2 週（創世記 1–11 章：Bereshit / Noach）",
    "pain_point": "傳統經文閱讀中，先祖動輒數百歲的數字容易被當作符號滑過，讀者難以直觀體會亞當與瑪土撒拉、以諾的同時代關係，以及洪水前後人類壽命急劇縮短的震撼斷層。",
    "features": [
      "互動水平甘特時空條：橫跨創世至亞伯拉罕時代，各代先祖壽命生卒年一目了然",
      "世代交疊即時比對：點選亞當即可查看誰與亞當生在同時代，親身見證挪亞之父拉麥與亞當同活 56 年",
      "洪水事件分界線：視覺化標註挪亞方舟大洪水年代，清晰呈現洪水前後生命週期的劇變"
    ],
    "tips": "讀到創世記第 5 章（塞特的後代）與第 11 章（閃的後代）家譜清單時，打開本圖比對，原本枯燥的「生與死」數字將化為立體鮮活的歷史見證。"
  },
  {
    "id": "genfam",
    "name": "創世記族長家族譜系圖",
    "subtitle": "Genesis Patriarchs Interactive Family Tree",
    "url": "https://shmuel310.github.io/genfam/",
    "qr": "companion_assets/qr_genfam.svg",
    "weeks": "第 3–12 週（創世記 12–50 章：Lech-Lecha 至 Vayechi）",
    "pain_point": "族長時代親屬脈絡錯綜複雜（亞伯拉罕同父異母之妹撒拉、夏甲、基土拉；以撒與利百加的以東與以色列分流；雅各的四位妻妾與十二支派血緣），極易混淆線索。",
    "features": [
      "全景動態分支樹狀圖：清晰區隔嫡庶親屬、婚姻盟約與各族繁衍支脈",
      "十二支派母親色彩標籤：利亞、拉結、辟拉、悉帕所生之子一鍵高亮辨析",
      "關鍵事件與經文快照：點擊任何家族成員，立即彈出其生平大事記、聖經稱號與關鍵經文出處"
    ],
    "tips": "讀到創世記 29–30 章（雅各生諸子）與 36 章（以掃後代）時，搭配本工具快速鎖定人物身份與地緣走向，不再為親屬關係頭暈。"
  },
  {
    "id": "calendar",
    "name": "猶太曆法與聖經節期全覽",
    "subtitle": "Biblical & Jewish Calendar Navigator",
    "url": "https://shmuel310.github.io/jewish_calendar/",
    "qr": "companion_assets/qr_calendar.svg",
    "weeks": "第 15 週 Bo、第 29–32 週（利未記節期篇章）及民數記、申命記節期經文",
    "pain_point": "現代基督徒習慣陽曆（太陽曆），面對聖經中的陰陽曆（太陰太陽曆）、正月亞筆月（尼散月）、宗教曆與民事曆雙軌制常感到抽象，難以建立節期與先知性預表的連結。",
    "features": [
      "雙環曆法同步對照：公曆 12 月份與猶太曆 12/13 個月份的即時動態對位",
      "耶和華七大節期指南：逾越節、無酵節、初熟節、七七節（五旬節）、吹角節、大贖罪日、住棚節",
      "彌賽亞救贖預表解析：春調節期如何應驗基督第一次降臨受害與復活，秋調節期如何預表第二次榮耀再來"
    ],
    "tips": "每逢讀到出埃及記 12 章（正月定為歲首）或利未記 23 章（耶和華的節期）時，開箱本工具核對當天公曆與猶太曆日期，深度體會神的神聖時鐘。"
  },
  {
    "id": "explorer",
    "name": "摩西五經互動資訊 · 613 誡命全覽",
    "subtitle": "Torah Interactive Reference & 613 Mitzvot",
    "url": "https://shmuel310.github.io/torah-explorer/",
    "qr": "companion_assets/qr_explorer.svg",
    "weeks": "全年度 54 週全年常備（涵蓋五卷書全覽、出埃及曠野行軍與律法矩陣）",
    "pain_point": "舊約律法散佈於出埃及記、利未記、民數記和申命記各處，條文數量龐大（613 條），讀者常不知某條誡命在何處重述、屬於哪類法典、或在歷史旅程中於何地頒佈。",
    "features": [
      "11 大研讀視角切換：包含 613 誡命檢索、歷史敘事時間軸、五書比對矩陣、妥拉之輪極坐標輪盤、法典氣泡矩陣",
      "出埃及與曠野 40 年行軍互動地圖：42 個行軍驛站地理座標與各站律法頒佈即時聯動",
      "三語經文與法典分類：每條誡命均具備希伯來文馬所拉文本、和合本中文與英文，並提供邁蒙尼德 14 大主題分類"
    ],
    "tips": "每週讀到該週篇章時，可在 Torah Explorer 中按「篇章」或「卷書」篩選，一鍵調出本週經文內所包含的全部誡命清單與原文對照。"
  }
],
  mitzvot: {
  "total": 613,
  "positive": 248,
  "negative": 365,
  "by_book": [
    {
      "book": "Gen",
      "name": "創世記",
      "count": 1,
      "pos": 1,
      "neg": 0,
      "pct": 0.2,
      "key": "生養眾多，遍滿地面 (創 1:28)",
      "focus": "起初盟約與家庭起點"
    },
    {
      "book": "Exo",
      "name": "出埃及記",
      "count": 111,
      "pos": 33,
      "neg": 78,
      "pct": 18.1,
      "key": "確立獨一真神與十誡安息 (出 20:2-17)",
      "focus": "救贖立約與會幕神居"
    },
    {
      "book": "Lev",
      "name": "利未記",
      "count": 247,
      "pos": 95,
      "neg": 152,
      "pct": 40.3,
      "key": "要愛人如己，我是耶和華 (利 19:18)",
      "focus": "至聖真神與祭禮成聖"
    },
    {
      "book": "Num",
      "name": "民數記",
      "count": 52,
      "pos": 18,
      "neg": 34,
      "pct": 8.5,
      "key": "衣裳四圍作繸子記念律例 (民 15:38-39)",
      "focus": "曠野行軍與事奉守則"
    },
    {
      "book": "Deu",
      "name": "申命記",
      "count": 200,
      "pos": 101,
      "neg": 99,
      "pct": 32.6,
      "key": "盡心、盡性、盡力愛耶和華 (申 6:5 示瑪)",
      "focus": "重申之約與生命抉擇"
    }
  ],
  "categories": [
    {
      "name": "知識基礎",
      "sub": "真神本體、愛神、敬畏神、悔改與讀律法",
      "count": 46
    },
    {
      "name": "偶像崇拜",
      "sub": "遠離偶像假神、行巫術、異教習俗之禁令",
      "count": 47
    },
    {
      "name": "敬拜時令",
      "sub": "安息日、節期安息、守節與曆法規例",
      "count": 43
    },
    {
      "name": "聖潔飲食",
      "sub": "潔淨動物、不可吃血、葷素不混之飲食條例",
      "count": 37
    },
    {
      "name": "誓願誓言",
      "sub": "許願、起誓、拿細耳人誓願與履行約言",
      "count": 25
    },
    {
      "name": "婚姻家庭",
      "sub": "婚禮、休書、亂倫禁令與家庭倫理守則",
      "count": 49
    },
    {
      "name": "農業土地",
      "sub": "安息年、禧年、遺落穀物留給窮人之慈惠法",
      "count": 51
    },
    {
      "name": "聖所事奉",
      "sub": "會幕聖所、祭司職分與祭壇之火管理",
      "count": 61
    },
    {
      "name": "獻祭之禮",
      "sub": "燔祭、素祭、平安祭、贖罪祭之獻祭細則",
      "count": 69
    },
    {
      "name": "祭司聖物",
      "sub": "初熟產物、十分之一與獻予神之聖物條例",
      "count": 38
    },
    {
      "name": "禮儀潔淨",
      "sub": "大痲瘋、死屍、漏症等禮儀不潔與浸洗潔淨",
      "count": 28
    },
    {
      "name": "人身損害",
      "sub": "殺人、傷人、公義審判、過失殺人與逃城",
      "count": 36
    },
    {
      "name": "財產賠償",
      "sub": "竊盜、借貸利息、誠實法碼天秤與商業道德",
      "count": 40
    },
    {
      "name": "司法戰爭",
      "sub": "法官公義、證人條例、兵法與王國統治之法",
      "count": 43
    }
  ]
}
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = COMPANION_DATA;
}
